
FROM python:3.10-slim-bullseye@sha256:e0724794e51d22cb7dd65382abc5855a0ade7027cd424f46a07b06496eec4537
WORKDIR /app
COPY requirements-live_test.txt ./
RUN pip install --no-cache-dir -r requirements-live_test.txt
COPY tests/live_test.py .
CMD ["python", "live_test.py"]