name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Build Docker images
      run: docker-compose build

    - name: Run Docker containers
      run: docker-compose up -d

    - name: Run integration tests
      run: |
        # Add your integration test commands here
        echo "Running integration tests"

    - name: Clean up
      run: docker-compose down

    - name: Send Discord notification for push event
      if: github.event_name == 'push'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"content": "Push event detected on main branch"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Send Discord notification for pull request event
      if: github.event_name == 'pull_request'
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"content": "Pull request event detected on main branch"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}
